<?php
return array (
  'app' => 'News',
  'model' => 'AdminIndex',
  'action' => 'index3',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '产品管理',
  'icon' => '',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'News',
      'model' => 'AdminIndex',
      'action' => 'index11',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '水表管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'a',
      'model' => 'a',
      'action' => 'a',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '电表管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'a',
      'model' => 'aa',
      'action' => 'a',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '燃气表管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'News',
      'model' => 'a',
      'action' => 'a',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '智能网关管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'aaa',
      'model' => 'aa',
      'action' => 'a',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '企业解决方案',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'sa',
      'model' => 'a',
      'action' => 'a',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '其他产品管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);