<?php
return array (
  'app' => 'News',
  'model' => 'AdminIndex',
  'action' => 'index3',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '产品管理',
  'icon' => '',
  'remark' => '',
  'listorder' => '1',
  'children' => 
  array (
    array (
      'app' => 'Product',
      'model' => 'AdminIndex',
      'action' => 'productW',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '水表管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Product',
      'model' => 'AdminIndex',
      'action' => 'productE',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '电表管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Product',
      'model' => 'AdminIndex',
      'action' => 'productG',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '燃气表管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Product',
      'model' => 'AdminIndex',
      'action' => 'productC',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '智能采集器管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Product',
      'model' => 'AdminIndex',
      'action' => 'productSolution',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '企业解决方案管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Product',
      'model' => 'AdminIndex',
      'action' => 'productOther',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '其他产品管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);